### PR TITLE
License project as Apache-2.0

### LINKED ISSUE #206: Add a license to the repo
Legally we still have the copyright to the repo, we probably want to give it up

### PR DESCRIPTION
**Pull request by danielg0**
License the codebase under an OS license to clarify the copyright situation

Closes #206

### CODE REVIEW

**Comment by danielg0** [comment]
I license my past and future contributions under the Apache-2.0 license.

**Comment by aDotInTheVoid** [comment]
I license my past and future contributions under the Apache-2.0 license.

**Comment by NathanielB123** [comment]
I license my past and future contributions under the Apache-2.0 license. (robot voice)

**Comment by sirjacobofglais** [comment]
"license my past and future contributions under the Apache-2.0 license. (robot voice)" - (robot voice)

**Comment by YRMYJASKA** [comment]
I license my past and future contributions under the Apache-2.0 license.

**Review by YRMYJASKA — APPROVED** [review]

**Comment by Euphoride** [comment]
I license my past and future contributions to this repository under the Apache-2.0 license.

**Pull request merged**
