### PR TITLE
Add Go coverage checking

### PR DESCRIPTION
**Pull request by danielg0**
Coverage checking requires generating a coverage profile during the test step, then we can filter out the total coverage from it.

Go also has the ability to generate a HTML coverage report. By uploading the coverage profile as an artifact, a new workflow (run when CI fails), can pull down that artifact, generate a coverage report and upload that.

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
What does this look like on failure?

**Comment by aDotInTheVoid** [comment]
https://github.com/gpuctl/gpuctl/actions/runs/7541270482

**Comment by danielg0** [comment]
Hmm, I've fixed the yaml file itself, and I didn't see a syntax error that time, but it still didn't run. Will it not til it's merged in?

**Comment by aDotInTheVoid** [comment]
Dont see why that should be. Might be better off just printing to console for now.

**Comment by danielg0** [comment]
> What does this look like on failure?



This isn't a failure case, but when there is failure, you can go in and see coverage at a per-function and global coverage percentages

**Pull request merged**
