### PR TITLE
Consolidate ssh code into `onboard`.

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Followup to #150

Advantages:

- Less code
- Single config type for all SSH stuff
- Only one place now needed to change HostKeyCallback
- Only one place where the `nohup` command is
- SSH session creation code consolidated

Disadvantages:

- The `onboard` name is now misleading.

### CODE REVIEW

**Comment by Euphoride** [comment]
Can we rename onboard to something better then given the name is now not applicable?

**Comment by aDotInTheVoid** [comment]
In a followup!

**Comment by Euphoride** [comment]
Not super happy approving a merge yet without naming changes given no reason the naming shouldn't be reflected now rather than later.

**Comment by aDotInTheVoid** [comment]
Gonna rename it to `tunnel`, in a followup PR this evening, but going to merge as-is, so each PR only does one thing.

**Pull request merged**
